---
- name: Download k9s
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v{{ version }}/k9s_Linux_x86_64.tar.gz"
    dest: "/tmp/"
    owner: root
    remote_src: yes

- name: Copy bin to bin
  copy:
    romete_src: /tmp/k9s
    dest: /bin/k9s
    owner: root
    group: root
    mode: '0744'