---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

workspace:
  path: /data/share/projects/git/ansible

steps:
- name: mirroring to github
  commands:
  - whoami
  - git push --mirror git@github.com:pwnlxrd/ansible.git
  - echo "mirroring done 👌"