---
- name: Enable K8s dns
  shell: microk8s.enable dns
  args:
    executable: /bin/bash

- name: Enable K8s ingress
  shell: microk8s.enable ingress
  args:
    executable: /bin/bash

- name: Enable K8s storage
  shell: microk8s.enable storage
  args:
    executable: /bin/bash

- name: Enable K8s registry
  shell: microk8s.enable registry
  args:
    executable: /bin/bash

- name: Enable K8s metrics-server
  shell: microk8s.enable metrics-server
  args:
    executable: /bin/bash

- name: Enable K8s rbac
  shell: microk8s.enable rbac
  args:
    executable: /bin/bash

- name: Enable K8s Dashboard
  shell: microk8s.enable dashboard
  args:
    executable: /bin/bash
  when: k8s_dashboard|default(False)|bool == True