---
- name: Add docker repository key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release  }} stable
    state: present
    filename: docker
    update_cache: yes

- name: Install docker and apt-fast packages
  apt:
    pkg: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose 
    state: present
