---
# tasks file for roles/server-init-role
- name: Install basic packages
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg
      - lsb-release
      - neovim
      - rsync
    state: present
    update_cache: yes

- name: Add docker repository key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release  }} stable
    state: present
    filename: docker
    update_cache: yes

- name: Install docker and apt-fast packages
  apt:
    pkg: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose 
    state: present

- name: copy configs .bashrc
  template:
    src: .bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: '0600'

- name: copy configs .bash_prompt
  template:
    src: .bash_prompt
    dest: /root/.bash_prompt
    owner: root
    group: root
    mode: '0600'

- name: copy configs welcome.sh
  template:
    src: welcome.sh
    dest: /root/welcome.sh
    owner: root
    group: root
    mode: '0700'

- name: copy configs .tmux.conf
  template:
    src: .tmux.conf
    dest: /root/.tmux.conf
    owner: root
    group: root
    mode: '0600'

- name: copy configs neovim
  copy:
    src: nvim/
    dest: /root/.config/nvim