---
- name: Install basic packages
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg
      - lsb-release
      - neovim
      - rsync
    state: present
    update_cache: yes
